### ISSUE TITLE
Allow different contexts

### ISSUE THREAD

**Issue by sympmarc** [spjeff/spcrud#1]
I'd suggest you make the context a variable so that you can pull data from other sites/webs.

In other words, not always _spPageContextInfo.webAbsoluteUrl.

M.

**Comment by spjeff** [comment]
Thanks Marc!   Really appreciate the code review and feedback.

Added "spcrud.setBaseUrl(webUrl)" line 50-63 on "spcrud.js" to change the working base URL.   By default it will try to infer the current SharePoint web for ease of use.

https://github.com/spjeff/spcrud/blob/master/spcrud.js
