### ISSUE TITLE
[Angular 6 + SharePoint Online] Debug outside of SharePoint Online (support)

### ISSUE THREAD

**Issue by christianwico** [spjeff/spcrud#3]
I'm getting 403's with every request I make from `localhost` unless I deploy the app to SharePoint Online.

I definitely expect this to be the case since I won't have my Office365 credentials available from `localhost`. I can live with the fact that I have to rebuild and re-deploy every time I make changes to the code, but it would be a huge convenience to not need to do so.

Is it possible that I could be able to debug my app from `ng serve` without getting 403-ed?

Code:
```typescript
    this.spCrud.setBaseUrl('office365 sharepoint site');
    this.spCrud.read('list name').then((res) => {
      const resArray = <any[]>res['d']['results'];

      resArray.forEach(listItem => {
        this.items.push(Ticket.initFromSpListResult(listItem));
      });
    }).catch(error => {
      console.error(error);
    });
```

**Comment by spjeff** [comment]
Try this out.

http://www.spjeff.com/2017/09/06/angular2-disable-cors-security-for-smooth-chrome-debug/
