### ISSUE TITLE
del function line 353

### ISSUE THREAD

**Issue by guirkgumbo** [spjeff/spcrud#5]
In the return statement "return this.http.post(url, localOptions)" url and localoptions are only passed. Data is required field for this  function so the function thinks localOptions is data.

This would be a proper fix "return this.http.post(url, '', localOptions)"

**Comment by spjeff** [comment]
Excellent.  Thank you, updated [spcrud.ts] with this change.

https://github.com/spjeff/spcrud/commit/79dfa19cd2acf903825fab72931dcc667d168bf2#diff-62b9e3b4f5e15f1cf6e9bccca3c856e7
